site_name: Maia's Documentation
theme:
  name: material
  logo: logo.png
  favicon: logo.png
  features:
    - navigation.tabs
extra_css:
  - extra.css

extra:
  social:
    - icon: fontawesome/brands/twitter
      link: https://www.maiaroos.com
    - icon: fontawesome/brands/facebook
      link: https://www.maiaroos.com
    - icon: fontawesome/brands/slack
      link: https://www.maiaroos.com
    - icon: fontawesome/brands/gitlab
      link: https://www.maiaroos.com
    - icon: fontawesome/brands/linkedin
      link: https://www.maiaroos.com

plugins:
  - search
  - git-revision-date-localized:
      type: date
  - build_plantuml:
      render: 'server' # or "local" for local rendering
      bin_path: '/usr/local/bin/plantuml' # ignored when render: server
      server: 'http://www.plantuml.com/plantuml' # offical plantuml server
      disable_ssl_certificate_validation: true # for self-signed and invalid certs
      output_format: 'svg' # or "png"
      diagram_root: 'docs/diagrams' # should reside under docs_dir
      output_folder: 'out'
      input_folder: 'src'
      input_extensions: '' # comma separated list of extensions to parse, by default every file is parsed
  - diagrams:
      file_extension: ".diagrams.py"
      max_workers: 5

markdown_extensions:
  - pymdownx.tasklist:
      custom_checkbox: true
  - admonition
  - pymdownx.details
  - pymdownx.superfences
  - plantuml_markdown:
      server: http://www.plantuml.com/plantuml
  

nav:
  - Home: 
    - Welcome: index.md
    - How To:
      - how-to/how-to-guides.md
    - Blog:
      - blog/blog.md

site_dir: public/